export {
  defineCalls,
  getCallMetadata,
  CALL_KINDS,
  GRAPHQL_OPERATION_KINDS,
} from '@callsheet/core';
export { call, mutation, query } from './builders';

export {
  buildSWRKey,
  extractFamilyFromSWRKey,
  extractIdentityFromSWRKey,
  getSWRAdapterConfig,
  isSWRCallKey,
  useMutation,
  usePreload,
  useQuery,
  useSWRAdapterConfig,
  useSWRMutation,
  useSWRPreload,
  useSWRQuery,
  withSWRConfig,
  matchesFamilyInSWRKey,
} from '@callsheet/core/swr';

export type {
  CallConfigContext,
  CallContext,
  CallKeyContext,
  CallMutateContext,
  Call,
  CallInputContext,
  CallInputOf,
  CallKind,
  CallKindOf,
  CallMetadata,
  CallOptions,
  CallOutputOf,
  CallSourceOf,
  CallsheetCustomSource,
  Family,
  FamilyPart,
  GraphQLOperationKind,
  HttpMethod,
  InvalidationConfig,
  InvalidationResolver,
  Key,
  KeyConfig,
  KeyContext,
  KeyPart,
  KeyResolver,
  MutationCall,
  MutationKind,
  MutationResultContext,
  QueryCall,
  QueryKind,
  RestSourceLike,
  SubscriptionOperationKind,
  TypedDocumentLike,
} from '@callsheet/core';
export type {
  MutationDefinitionOptions,
  QueryDefinitionOptions,
} from './definition-options';

export type {
  ExecuteCall,
  ExecuteCallContext,
  ExecuteCallMetadata,
  ExecuteCallMiddleware,
  ExecuteCallNext,
  ExecuteCallOverrides,
  MutationCallOptions,
  QueryCallOptions,
  SWRAdapterConfig,
  SWRCallKey,
  SWRKeyIdentity,
  SWRKeyIdentitySegment,
  SWRMutationKey,
} from '@callsheet/core/swr';
